Models/Invite.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace cyberpet.Models
{
    public class Invite
    {
        [Key]
        public Guid Id { get; set; }
        
        public Household Household { get; set; }
        
        public ApplicationUser Inviter { get; set; }
        public string InviteeEmail { get; set; }
        public int HouseholdId { get; set; }
        
    }
}

Controllers/InviteController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using cyberpet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace cyberpet.Controllers
{
    [ApiController]
    public class InviteController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> userManager;  

        public InviteController(ApplicationDbContext dbContext, UserManager<ApplicationUser> um)
        {
            _dbContext = dbContext;
            userManager = um;
        }
        
        [HttpGet]
        [Route("/acceptInvite/{inviteId}")]
        public async Task<IActionResult> Index(Guid inviteId)
        {
            var invite = await _dbContext.Invites.Include(i => i.Household)
                .Include(i => i.Inviter).FirstOrDefaultAsync(i => i.Id == inviteId);

            if (invite == null)
            {
                return NotFound();
            }

            var invitee = await userManager.FindByEmailAsync(invite.InviteeEmail);

            if (invitee == null)
            {
                // need to make new user
                ViewData["newUser"] = true;
            }
            else
            {
                ViewData["newUser"] = false;
            }
            
            ViewData["invite"] = invite;

            return View();
        }

        [HttpPost]
        [Route("acceptInvite/{inviteId}")]
        public async Task<IActionResult> CreateUser(Guid inviteId, [FromForm] RegisterModel model)
        {
            var userExists = await userManager.FindByNameAsync(model.Email);  
            if (userExists != null)  
                return StatusCode(StatusCodes.Status500InternalServerError, new Response { Status = "Error", Message = "User already exists!" });  
  
            Debug.WriteLine("user exists");
            ApplicationUser user = new ApplicationUser()  
            {  
                Email = model.Email,  
                SecurityStamp = Guid.NewGuid().ToString(),
                UserName = model.Email,
                DisplayName = model.DisplayName
            };

            ViewBag.inviteId = inviteId;
            
            var result = await userManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
            {
                ViewBag.essage = "User creation failed! Please check user details and try again.";
            }
            else
            {
                Console.WriteLine("user created");
                ViewBag.message = "User Created Successfully!";
            }
            
            return View();
        }

        [HttpPatch]
        [Route("acceptInvite/{inviteId}")]
        public async Task<IActionResult> AddToHousehold(Guid inviteId)
        {
            var invite = await _dbContext.Invites.FirstOrDefaultAsync(i => i.Id == inviteId);
            if (invite == null)
                return NotFound();
            
            var user = await userManager.FindByNameAsync(invite.InviteeEmail);
            if (user == null)
                return NotFound();

            var hu = new HouseholdUser
            {
                Household = invite.Household,
                HouseholdId = invite.HouseholdId,
                IsAdmin = false,
                User = user
            };
            var result = await _dbContext.HouseholdUsers.AddAsync(hu);
            if (result == null)
                return NotFound();

            _dbContext.Invites.Remove(invite);
            await _dbContext.SaveChangesAsync();
            
            Console.WriteLine("Invite accepted");
            return Ok();
        }
    }
}

Views/Invite/CreateUser.cshtml
@model dynamic
@using cyberpet.Models
@using static cyberpet.Models.Invite
@using static cyberpet.Models.RegisterModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Invite</h1>
    @{
        var msg = ViewBag.message;
    }
    <h2>@msg</h2>
    <button onclick="goBack()">Go Back to Invite</button>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>
</body>
</html>

Views/Invite/Index.cshtml
@model dynamic
@using cyberpet.Models
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@using static cyberpet.Models.Invite
@using static cyberpet.Models.RegisterModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Invite</title>
</head>
<body>
<div>
    <h1>Invite</h1>
    @{
        var data = (Invite) ViewData["invite"];
        var newUser = (bool) ViewData["newUser"];
    }
    <h2>Invite ID: @data.Id</h2>
    <h3>You have been invited to Household @data.Household.Name by @data.Inviter.DisplayName</h3>
    @if (newUser)
    {
        <div class="row">
            <div class="col-md-9">
                <form asp-controller="Invite" asp-action="CreateUser" method="post">
                    <div class="form-group">
                        <label asp-for="DisplayName" class="control-label">Display Name</label>
                        <input asp-for="DisplayName" class="form-control" name="DisplayName"/>  
                        <span asp-validation-for="DisplayName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label">Email</label>
                        <input asp-for="Email" class="form-control" value="@data.InviteeEmail" name="Email"/>  
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label">Password</label>
                        <input asp-for="Password" class="form-control" name="Password"/>  
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">  
                        <button type="submit">Create new user</button>
                    </div>
                    <b>@ViewBag.message</b>
                </form>
            </div>
        </div>
    }
    
    else
    {
        <button onclick="acceptInvite()">Accept Invite</button>
    }
</div>
<script>
    async function acceptInvite() {
        const inviteId = '@(ViewBag.inviteId)';
        console.log(inviteId);
        const res = await fetch("", {
            method: "patch",
            headers: {
                "Content-Type": "application/json"
            }
        });
        
        const x = await res.json();
        console.log(x);
    }
</script>
</body>
</html>